"""AgentForge MCP server template.

Every tool in this server follows the same three rules:
  1. Authenticate the caller and check their scope.
  2. Screen the input for prompt injection.
  3. Mask PII in the output.

Run it:
    pip install -r requirements.txt
    AGENTFORGE_TOKENS="tok-alice:alice:tools.read,tools.write;tok-bob:bob:tools.read" \
        python -m agentforge.server

Then point any MCP client at it.
"""

from __future__ import annotations

from mcp.server.fastmcp import FastMCP

from .auth import AuthError, TokenStore, require_scope
from .guardrails import BlockedContent, mask_pii, screen_prompt

mcp = FastMCP("agentforge")
_tokens = TokenStore()


def _user(auth_token: str | None, scope: str):
    """Authenticate and authorize in one call. Raises AuthError on failure."""
    user = _tokens.authenticate(auth_token)
    require_scope(user, scope)
    return user


@mcp.tool()
def search_docs(query: str, auth_token: str) -> str:
    """Search the internal docs. Requires the tools.read scope."""
    user = _user(auth_token, "tools.read")
    screen_prompt(query)
    # In your server, query the real docs here. The guardrail stays
    # on the output path no matter where the text came from.
    result = f"Docs for '{query}' (requested by {user.id}): contact jane.doe@example.com for access."
    return mask_pii(result)


@mcp.tool()
def run_report(name: str, auth_token: str) -> str:
    """Generate a report. Requires the tools.write scope."""
    user = _user(auth_token, "tools.write")
    screen_prompt(name)
    result = f"Report '{name}' generated by {user.id}."
    return mask_pii(result)


def main() -> None:
    mcp.run()


if __name__ == "__main__":
    main()
